package com.gsccs.cmcc.info.dao;

import com.gsccs.cmcc.info.model.ProductT;
import com.gsccs.cmcc.info.model.ProductTExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ProductTMapper {

	int countByExample(ProductTExample example);

	int deleteByExample(ProductTExample example);

	int deleteByPrimaryKey(String id);

	int insert(ProductT record);

	List<ProductT> selectPageByExample(ProductTExample example);

	List<ProductT> selectByExample(ProductTExample example);

	
	ProductT selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table xxbs_product
	 * 
	 * @mbggenerated Fri Apr 01 18:45:16 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ProductT record,
			@Param("example") ProductTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table xxbs_product
	 * 
	 * @mbggenerated Fri Apr 01 18:45:16 CST 2016
	 */
	int updateByExample(@Param("record") ProductT record,
			@Param("example") ProductTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table xxbs_product
	 * 
	 * @mbggenerated Fri Apr 01 18:45:16 CST 2016
	 */
	int updateByPrimaryKeySelective(ProductT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table xxbs_product
	 * 
	 * @mbggenerated Fri Apr 01 18:45:16 CST 2016
	 */
	int updateByPrimaryKey(ProductT record);
}