package com.gsccs.cmcc.info.dao;

import com.gsccs.cmcc.info.model.PropT;
import com.gsccs.cmcc.info.model.PropTExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PropTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxbs_product_prop
     *
     * @mbggenerated Fri Apr 01 18:45:16 CST 2016
     */
    int countByExample(PropTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxbs_product_prop
     *
     * @mbggenerated Fri Apr 01 18:45:16 CST 2016
     */
    int deleteByExample(PropTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxbs_product_prop
     *
     * @mbggenerated Fri Apr 01 18:45:16 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxbs_product_prop
     *
     * @mbggenerated Fri Apr 01 18:45:16 CST 2016
     */
    int insert(PropT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxbs_product_prop
     *
     * @mbggenerated Fri Apr 01 18:45:16 CST 2016
     */
    int insertSelective(PropT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxbs_product_prop
     *
     * @mbggenerated Fri Apr 01 18:45:16 CST 2016
     */
    List<PropT> selectPageByExample(PropTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxbs_product_prop
     *
     * @mbggenerated Fri Apr 01 18:45:16 CST 2016
     */
    PropT selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxbs_product_prop
     *
     * @mbggenerated Fri Apr 01 18:45:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") PropT record, @Param("example") PropTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxbs_product_prop
     *
     * @mbggenerated Fri Apr 01 18:45:16 CST 2016
     */
    int updateByExample(@Param("record") PropT record, @Param("example") PropTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxbs_product_prop
     *
     * @mbggenerated Fri Apr 01 18:45:16 CST 2016
     */
    int updateByPrimaryKeySelective(PropT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxbs_product_prop
     *
     * @mbggenerated Fri Apr 01 18:45:16 CST 2016
     */
    int updateByPrimaryKey(PropT record);
}